# Site
name: '育儿有道'
description: '幼师资源站'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'funkidsvip@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           JUN TAO
      nickname:       poka-daddy
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar1.jpg
      bio:            "在线教育公司产品经理，儿童玩具爱好者。观察很久我发现优秀的妈妈都是“长期主义者”!"
      email:          funkidsvip@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           章年柒
      nickname:       poka-mom
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "幼儿园教研，前美吉姆老师，高级育婴师!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 

# resourse
websites:
  sal:
    name:           JUN TAO
    nickname:       poka-daddy
    site:           https://www.wowthemes.net
    avatar:         assets/images/avatar1.jpg
    bio:            "在线教育公司产品经理，儿童玩具爱好者。观察很久我发现优秀的妈妈都是“长期主义者”!"
    email:          funkidsvip@gmail.com
    twitter:        https://twitter.com/wowthemesnet

  jane:
    name:           章年柒
    nickname:       poka-mom
    site:           https://www.wowthemes.net
    avatar:         assets/images/avatar2.jpg
    bio:            "幼儿园教研，前美吉姆老师，高级育婴师!"
    email:          fakemail@gmail.com
    twitter:        https://twitter.com/wowthemesnet



# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Poka爸
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]